"""baseline schema

Revision ID: 437d8ae8a0c7
Revises:
Create Date: 2026-08-17 14:00:12.427556

"""

# Modern union syntax and sorted imports, so a generated migration passes
# `ruff check .` unedited. The stock template emits `typing.Union` and an
# unsorted import block, which fails the repo's UP and I rules on arrival.
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "437d8ae8a0c7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("cv_path", sa.String(), nullable=True),
        sa.Column("cover_letter_path", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("screenshot_path", sa.String(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("outcome_recorded_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_intel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_normalized", sa.String(), nullable=False),
        sa.Column("total_petitions", sa.Integer(), nullable=False),
        sa.Column("approved_petitions", sa.Integer(), nullable=False),
        sa.Column("denied_petitions", sa.Integer(), nullable=False),
        sa.Column("ml_ai_petitions", sa.Integer(), nullable=False),
        sa.Column("median_salary", sa.Float(), nullable=True),
        sa.Column("avg_salary", sa.Float(), nullable=True),
        sa.Column("approval_rate", sa.Float(), nullable=False),
        sa.Column("sponsor_tier", sa.String(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("years_active", sa.JSON(), nullable=False),
        sa.Column("top_roles", sa.JSON(), nullable=False),
        sa.Column("states", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_intel", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_company_intel_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_company_intel_name_normalized"), ["name_normalized"], unique=False
        )

    op.create_table(
        "graph_edges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_node_id", sa.Integer(), nullable=False),
        sa.Column("to_node_id", sa.Integer(), nullable=False),
        sa.Column("edge_type", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("graph_edges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_graph_edges_edge_type"), ["edge_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_graph_edges_from_node_id"), ["from_node_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_graph_edges_to_node_id"), ["to_node_id"], unique=False)

    op.create_table(
        "graph_nodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("label_normalized", sa.String(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("graph_nodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_graph_nodes_label"), ["label"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_graph_nodes_label_normalized"), ["label_normalized"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_graph_nodes_node_type"), ["node_type"], unique=False)

    op.create_table(
        "h1b_petitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employer_name", sa.String(), nullable=False),
        sa.Column("employer_name_normalized", sa.String(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=False),
        sa.Column("job_title_normalized", sa.String(), nullable=False),
        sa.Column("wage_from", sa.Float(), nullable=True),
        sa.Column("wage_to", sa.Float(), nullable=True),
        sa.Column("wage_unit", sa.String(), nullable=False),
        sa.Column("case_status", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("worksite_state", sa.String(), nullable=False),
        sa.Column("worksite_city", sa.String(), nullable=False),
        sa.Column("is_ml_role", sa.Boolean(), nullable=False),
        sa.Column("source_file", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("h1b_petitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_h1b_petitions_employer_name"), ["employer_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_h1b_petitions_employer_name_normalized"),
            ["employer_name_normalized"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_h1b_petitions_year"), ["year"], unique=False)

    op.create_table(
        "job_enrichments",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("sponsorship_prob", sa.Float(), nullable=True),
        sa.Column("sponsorship_tier", sa.String(), nullable=True),
        sa.Column("predicted_salary", sa.Integer(), nullable=True),
        sa.Column("salary_low", sa.Integer(), nullable=True),
        sa.Column("salary_high", sa.Integer(), nullable=True),
        sa.Column("semantic_score", sa.Float(), nullable=True),
        sa.Column("uscis_petitions", sa.Integer(), nullable=True),
        sa.Column("uscis_approval_rate", sa.Float(), nullable=True),
        sa.Column("uscis_sponsor_tier", sa.String(), nullable=True),
        sa.Column("enriched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "job_labels",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("user_rationale", sa.String(), nullable=True),
        sa.Column("labeled_at", sa.DateTime(), nullable=False),
        sa.Column("score_at_label_time", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("salary_raw", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("visa_label", sa.String(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("description_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "score_results",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("sub_scores", sa.JSON(), nullable=False),
        sa.Column("matched_skills", sa.JSON(), nullable=False),
        sa.Column("missing_skills", sa.JSON(), nullable=False),
        sa.Column("recommended_emphasis", sa.JSON(), nullable=False),
        sa.Column("visa_compatible", sa.Boolean(), nullable=False),
        sa.Column("visa_notes", sa.String(), nullable=False),
        sa.Column("overall_rationale", sa.Text(), nullable=False),
        sa.Column("scored_at", sa.DateTime(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("score_results")
    op.drop_table("jobs")
    op.drop_table("job_labels")
    op.drop_table("job_enrichments")
    with op.batch_alter_table("h1b_petitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_h1b_petitions_year"))
        batch_op.drop_index(batch_op.f("ix_h1b_petitions_employer_name_normalized"))
        batch_op.drop_index(batch_op.f("ix_h1b_petitions_employer_name"))

    op.drop_table("h1b_petitions")
    with op.batch_alter_table("graph_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_nodes_node_type"))
        batch_op.drop_index(batch_op.f("ix_graph_nodes_label_normalized"))
        batch_op.drop_index(batch_op.f("ix_graph_nodes_label"))

    op.drop_table("graph_nodes")
    with op.batch_alter_table("graph_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_edges_to_node_id"))
        batch_op.drop_index(batch_op.f("ix_graph_edges_from_node_id"))
        batch_op.drop_index(batch_op.f("ix_graph_edges_edge_type"))

    op.drop_table("graph_edges")
    with op.batch_alter_table("company_intel", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_company_intel_name_normalized"))
        batch_op.drop_index(batch_op.f("ix_company_intel_name"))

    op.drop_table("company_intel")
    op.drop_table("applications")
    # ### end Alembic commands ###
